### ISSUE TITLE
G::Individual->as_string()

### ISSUE THREAD

**Issue by nigelhorne** [pjcj/Gedcom.pm#10]
Would it be possible to add a method as_string() to Gedcom::Individual that returns a string such as

Lastname, Firstname MiddleName Suffixes (dob-dod)

If you want, I can have a go at writing one.

**Comment by pjcj** [comment]
Thanks for the suggestion!

My main concern with adding this is that we're not going to be able to get a function which works for everyone.  Or perhaps even for most people.  I wasn't even sure about adding the Individual::name method for this very reason.

And I'm not particularly keen on adding some sort of interface like strftime when writing your own subroutine is so easy.

I'm also not enamoured of the name, but that's a less important concern.

If you can convince me of the utility of a specific format then I am not completely against the idea, but I think I'll need some convincing.

**Comment by nigelhorne** [comment]
It turned out to be more complicated than I expected because of the lack of constraints in the Gedcom specification.  So whilst I have something which works for me, I'm not so sure it'll be of use to anyone else so feel to close with "won't fix".

**Comment by pjcj** [comment]
OK, let's close this then.  It's a nice idea but I think you're right about the scope of the problem.

But thanks anyway.
