### ISSUE TITLE
Gedcom::Comparison is noisy

### ISSUE THREAD

**Issue by nigelhorne** [pjcj/Gedcom.pm#11]
How do I tell G::C to give me a result without the debugging information?

**Comment by pjcj** [comment]
Are you finding Gedcom::Comparison useful?  I must admit, that the reason I initially started writing Gedcom.pm was to be able to compare and merge GEDCOM files.  Unfortunately I have never quite got that far, but Gedcom::Comparison was a step in that direction.  It's not really finished though.

In any case, I have quietened it with e2bdef625dadeae78a23a0f9d861fd20e8a7ffff.

Thanks for the report.

**Comment by nigelhorne** [comment]
I'd like to use it in my Gedcom::Individual::relationship method since I believe that would be a fairer comparison than simply seeing if the objects point to the same place, so yes I am interested, thanks!
