### ISSUE TITLE
residence

### ISSUE THREAD

**Issue by nigelhorne** [pjcj/Gedcom.pm#13]
What is the return value for a person.

If I try this:

    foreach my $person($ged->individuals()) {
        my @residence = $person->residence();

	foreach my $residence(@residence) {
	    print $residence->place(), "\n";
	   }
       }
    }

I get 'Can't locate object method "place" via package "Marital Status: SingleRelation to Head of House: Child"'

That "Marital Status" output is the text associated with the record, like this:

1 RESI Marital Status: MarriedRelation to Head of House: Wife
2 DATE 02 Apr 1911
2 PLAC Sculcoates, Yorkshire-East Riding, England
2 SOUR @S-1796549337@
3 PAGE Class: RG14; Piece: 28629
3 _APID 1,2352::30354710

I want code that will print "Sculcoates, Yorkshire-East Riding, England".

**Comment by pjcj** [comment]
Thanks very much for reporting this with an example.

There are two problems here.

The first problem is that your GEDCOM file is invalid.  ( I am stating this as a fact, and I believe it is true, but I may be mistaken.)  The GEDCOM standard doesn't allow for text after RESI (the "Marital Status: MarriedRelation to Head of House: Wife" part of the line).  If you remove that text then your example should work as your are expecting.  You can add any number of NOTEs to the RESI and this is probably where such a comment should appear.

The second problem is that Gedcom.pm didn't catch that.

I'll leave this ticket open until that second problem is fixed, but in the meantime I suggest ensuring that your GEDCOM file is valid.  Was the file generated by some software, or is it one that you have created by hand?

**Comment by nigelhorne** [comment]
Thanks for your reply.  The GEDCOM file was exported from ancestry.com.  I didn't change it.

**Comment by pjcj** [comment]
I have updated the validation method so this it now reports this as a problem (e95a4d3e19d4d92192e69a993e34c6a5df1af52c).  I also fixed up the line numbers which were being reported incorrectly.

Not much I can do about ancestry.com, but we could make an ancestry-specific grammar which allowed this.  If this seems like a good idea and you'd like to follow up on it then please open a new ticket.

Thanks!

**Comment by nigelhorne** [comment]
Actually since the post I've been able to write a workaround which is something like this:

> 			my $index = 0;
> 			foreach my $residence(@residences) {
> 				$index++;
> 				if(!ref($residence)) {
> 					my $r = $person->tag_record('EVEN', $index);
> 					if(ref($r) eq 'Gedcom::Record') {
> 						$residence = $r;
> 					} else {
> 						$r = $person->record(['residence', $index]);
> 						if(ref($r) eq 'Gedcom::Record') {
> 							$residence = $r;
> 						} else {
> 							red_warning({ person => $person, warning => "Residence record is just description ($residence), infomation has been lost" });
> 						}
> 					}
> 				}
> 				if(ref($residence) eq 'Gedcom::Record') {

It's not nice, but it does work!
