### ISSUE TITLE
_prim

### ISSUE THREAD

**Issue by nigelhorne** [pjcj/Gedcom.pm#14]
Any plans to support what I presume are the non-standard tag _PRIM mentioned at http://wiki-en.genealogy.net/GEDCOM/OBJE-Tag?

It appears to me the FindMyPast.com does support them, and it would help if you did as well, so that I could pick the profile image from a set of objects.

**Comment by nigelhorne** [comment]
Actually, I suspect that supporting user-defined tags may be enough.  See
http://wiki-en.genealogy.net/GEDCOM/_UserDef-Tag

**Comment by pjcj** [comment]
Thanks very much for reporting this and sorry for not replying sooner.  User-defined tags should already be supported.  But obviously something is not working for you.  I am going to close this ticket, but if you find the current implementation doesn't do what you want or you find a bug in the implementation, please feel free to open it again.  If you do that, please include the code you are using to access the _PRIM tag.

**Comment by nigelhorne** [comment]
Try as I might I work out how to do this.  Any chance of an example in the documentation?

Alternatively take a look around line 1560 of https://github.com/nigelhorne/ged2html

**Comment by nigelhorne** [comment]
"please feel free to open it again".  That's not possible on Github.  Perhaps the code owner can do that but not a user, so I'm going to have to open a new issue.
