### ISSUE TITLE
_prim(2)

### ISSUE THREAD

**Issue by nigelhorne** [pjcj/Gedcom.pm#16]
"please feel free to open it again". That's not possible on Github. Perhaps the code owner can do that but not a user, so I'm going to have to open a new issue

Try as I might I work out how to do primary flags.. Any chance of an example in the documentation?

Alternatively take a look around line 1569 of https://github.com/nigelhorne/ged2html where I've put it lots of tests to try to notice a "primary" flag, but that never triggers.

**Comment by pjcj** [comment]
Sorry about that - I imagined that the creator of the ticket would be able to reopen it.

From the page at http://wiki-en.genealogy.net/GEDCOM/OBJE-Tag is seems that _PRIM is a sub-record of OBJE, so your code should look like:

  my $prim = $person->obje->get_value("_PRIM");

I have added _PRIM to the test suite, and put an example code snippet in the ged script.

I have merged this in 55f14d744ff4c1ad45c44d999fc3cdd3832b5578.

Hope this helps!

**Comment by nigelhorne** [comment]
That gives "Non standard record of type _PRIM requested at"

However, I've found that this snippet works:

	my $profile_object = $person->tag_record('_PROF');
			if($profile_object) {
				$profile_object = $person->resolve_xref($profile_object->value());
			}

**Comment by pjcj** [comment]
The "Non standard record of type _PRIM requested at" warning should not occur if you have 55f14d7 but that is not released yet so I presume you weren't using the very latest version.  If you find that you are still getting that warning later then please open a new ticket for that.

Thanks!
