### ISSUE TITLE
are TRLR lines handled?

### ISSUE THREAD

**Issue by nigelhorne** [pjcj/Gedcom.pm#22]
I'm seeing parser errors with the Gedcom files at https://webtreeprint.com/tp_famous_gedcoms.php

The errors are "Can't parse line: 0 TRLR".

**Comment by coret** [comment]
This means the TRLR line doesn't have a line terminator (which is mandatory).

**Comment by pjcj** [comment]
Whilst correct, that wasn't a particularly helpful comment.  I've added a commit to the `dev` branch to fix that and it will be in the next release.
