### ISSUE TITLE
Is old install/System.pm in a separate distribution (or could it be)?

### ISSUE THREAD

**Issue by cxw42** [pjcj/Gedcom.pm#23]
I found <https://metacpan.org/pod/System>, source [here](https://raw.githubusercontent.com/pjcj/Gedcom.pm/a2bb374c37af8c5bbdb7d78ffaee9374e41176fa/install/System.pm).  It is just right for my use case --- thanks!  I see from [this](https://github.com/pjcj/Gedcom.pm/blob/a2bb374c37af8c5bbdb7d78ffaee9374e41176fa/README.md) that the license is `perl5`.  Is it in a distribution of its own?  I can't find one.  If not, would you mind if I modernized it a bit and distributed it?  (With appropriate credit, of course.)  Much appreciated!

**Comment by pjcj** [comment]
Hello.  Wow, that's a bit of a blast from the past - 20 years old :)

Yes, the licence is the same as Perl.  And no, it's not in its own distribution.  You're very welcome to do what you would like with it - it certainly could do with a little modernisation!

**Comment by cxw42** [comment]
@pjcj Thank you!  `System::Explain` will be on its way shortly :) .
