### ISSUE TITLE
Unclear License

### ISSUE THREAD

**Issue by perlpunk** [pjcj/Gedcom.pm#25]
https://metacpan.org/source/PJCJ/Gedcom-1.21/META.yml says:

    license: unknown

https://metacpan.org/source/PJCJ/Gedcom-1.21/META.json says:

    "license" : [
       "unknown",
       "perl_5"
    ],

We stumbled upon this while maintaining the perl modules repository for openSUSE.

**Comment by pjcj** [comment]
That's pretty ugly, yes.

This code is older than the META standard so these files are automatically generated.  So I suppose one could argue that this is a bug in MakeMaker or whatever is being used to generate those files.

Fortunately the licence is clear in the actual docs.

I've added 7b666080f4ac7c8f263468051f3ae80617e94a06 which, I hope, solves the problem.

Thanks very much for letting me know!

**Comment by pjcj** [comment]
Now on CPAN as version 1.22.

**Comment by perlpunk** [comment]
Thanks.
Unfortunately the META.yml still has `license: open_source`, but that's probably a problem of MakeMaker
