### ISSUE TITLE
Empty test in callback causes processing error

### ISSUE THREAD

**Issue by cacack** [pjcj/Gedcom.pm#4]
It seems if you perform a test within the callback subroutine of the new constructor without actually doing anything, it breaks gedcom processing.  I tested with the following code.  Uncomment the print statement within the callback and processing works.  Dumping the gedcom object looks like it just contains the grammer, no data.

```perl
#!/usr/bin/env perl

use strict;
use warnings;

use Gedcom;

my $GedcomFile = $ARGV[0] and -r $ARGV[0]
   or die "You must specify a gedcom file to process.\n";

my $Gedcom = Gedcom->new(
   gedcom_file       => $GedcomFile,
   callback          => \&Status,
);

my @Individuals = $Gedcom->individuals;
print "Found " . @Individuals . " people.\n";

sub Status {
	my ($Title, $Txt1, $Txt2, $Current, $Total) = @_;
   if (@_) {
      #print "[$Current/$Total] $Title $Txt2.\n";
   }
}
```

**Comment by pjcj** [comment]
Wow - I am /really/ late responding to this.  I am so sorry!

And more bad news: it's a feature, not a bug.

The return value of the callback subroutine determines whether or not processing continues.  In the case of your Status() subroutine the return is not immediately obvious.  With the print statement there the return value of the whole subroutine is the return value of the print statement, which is true if the print succeeds.  Without the print the return value is rather unclear and in this case is false.

The easy workaround is just to add "return 1;" at the end of the subroutine.

Thanks for taking the time to report this, and sorry again for taking such a long time to reply.
